### PR TITLE
Language modeling

### PR DESCRIPTION
**Pull request by kalvinchang**
In this PR, we train a LSTM-based language model at the phoneme level to learn distributional information about phonetic similarity. To ensure that the model is encoding phonetic information, we use panphon as static feature embeddings for the language model. 

To obtain pooled embeddings for a word, we input panphon features for that word (a feature matrix) into the LSTM and extract the last token's output at final layer of the LSTM, similar to the pooling method we employ in the metric learning prototype (#4).

### CODE REVIEW

**Comment by kalvinchang** [comment]
Both of our lab machines are down. Could anyone run my code? Thanks!

**Comment by kalvinchang** [comment]
Way to speed up the model: pass in the entire sequence into the RNN instead of doing it phoneme by phoneme

**Comment by kalvinchang** [comment]
I tested with a truncated set of 10,000 words

initial results:
image

image


image

* the initial spearman was never beaten, but pearson did improve over time
* Best pearson: 0.6512
* Best spearman's: .3698

**Comment by zouharvi** [comment]
I'd view this positively. Sure, it didn't work better than using a rule-based phonetic guiding metric to train the embeddings. But just based on language modelling, it correlates nontrivially with that metric.

**Comment by kalvinchang** [comment]
Running a sweep on wandb: https://wandb.ai/llab-reconstruction/phonological-pooling/sweeps/xci3tbxf

- 0.7446 is the best Spearman's correlation seen thus far (Pearson's 0.7661)
- Reinstalled pytorch on our lab machine so that it can use the GPUs

**Comment by kalvinchang** [comment]
Added masked phoneme modeling

**Comment by zouharvi** [comment]
@kalvinchang There was some more reorganizing. Could you resolve the conflicts? Probably all your files should be in `models/language_modelling/`

**Comment by kalvinchang** [comment]
Best Spearman correlation seen with masked phoneme modeling (embedding size 24): 0.8875 (on 10K subset of Spanish)

**Comment by kalvinchang** [comment]
in 429d145, 
I moved all necessary files to the models/language_modeling folder

I will refactor  only after I get all the results in

**Comment by kalvinchang** [comment]
best spearman's (after making the embeddings more dense - 300 dim) so far: 0.9091 (on 10K subset of Spanish)

**Pull request merged**
